Fix flaky test by setting the join timeout to infinite (#1149)
- One of the tests added in #1145 is flaky:
https://github.com/openvinotoolkit/datumaro/actions/runs/6156803415/job/16706221640
```console
=========================== short test summary info ============================
FAILED tests/unit/test_util.py::MultiProcUtilTest::test_raise_exception_in_main_thread
= 1 failed, 1493 passed, 38 skipped, 2 xfailed, 48148 warnings in 407.34s (0:06:47) =
tests-py38-darwin: exit 1 (462.14 seconds) /Users/runner/work/datumaro/datumaro> python -m pytest -v --csv=/Users/runner/work/datumaro/datumaro/.tox/results-tests-py38-darwin.csv tests/unit --cov --cov-report=xml pid=4536
.pkg: _exit> python /Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  tests-py38-darwin: FAIL code 1 (793.18=setup[331.04]+cmd[462.14] seconds)
  evaluation failed :( (803.78 seconds)
```
- This is because `join_timeout` is too short, so that the main thread
tries to assert the error logs before they are created.
- To fix it, set `join_timeout=None` to wait it infinitely until the
producer thread terminates.

Signed-off-by: Kim, Vinnam <vinnam.kim@intel.com>